# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

# trigger:
# - master

# pool:
#   vmImage: 'ubuntu-latest'

variables:
  var1: Windows

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: Test
  jobs:
  - job: TestOnWindows
    variables:
      var1: Windows
    steps:
    - script: echo Testing on $(var1)!  secret = $(secretPassword)
  - job: TestOnLinux
    variables:
      var1: Linux
    steps:
    - script: echo Testing on $(var1)!  secret = $(secretPassword)
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!

# - task: Maven@3
#   inputs:
#     mavenPomFile: 'pom.xml'
#     mavenOptions: '-Xmx3072m'
#     javaHomeOption: 'JDKVersion'
#     jdkVersionOption: '1.8'
#     jdkArchitectureOption: 'x64'
#     publishJUnitResults: true
#     testResultsFiles: '**/surefire-reports/TEST-*.xml'
#     goals: 'package'
